# Generated by Django 4.0.6 on 2022-07-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issueTracker', '0002_alter_users_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
