# Generated by Django 4.0.6 on 2022-07-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issueTracker', '0003_alter_projects_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
