# Generated by Django 4.0.6 on 2022-07-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issueTracker', '0004_alter_projects_author_user_id_alter_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
