# Generated by Django 4.0.6 on 2022-07-26 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issueTracker', '0005_alter_users_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='author_user_id',
            new_name='author',
        ),
    ]
