# Generated by Django 4.0.6 on 2022-07-27 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issueTracker', '0007_rename_assignee_user_id_issues_assignee_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributors',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='contributors',
            old_name='user_id',
            new_name='user',
        ),
    ]
